// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXSdBi_ImQfYl2UbCtU1oYQTwg0Fj8iG0',
    appId: '1:1065959458599:web:106223d96b629dec760b02',
    messagingSenderId: '1065959458599',
    projectId: 'petbhore',
    authDomain: 'petbhore.firebaseapp.com',
    storageBucket: 'petbhore.appspot.com',
    measurementId: 'G-L0VZ83N72Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlEeJrAATnx3s7oxwdDvRGtZeyFrsXuQE',
    appId: '1:1065959458599:android:ddd29226d8249dc2760b02',
    messagingSenderId: '1065959458599',
    projectId: 'petbhore',
    storageBucket: 'petbhore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmXE61oAfj2_yu0TYuh2MmlTicQjxRpM',
    appId: '1:1065959458599:ios:d05ba1a51819356b760b02',
    messagingSenderId: '1065959458599',
    projectId: 'petbhore',
    storageBucket: 'petbhore.appspot.com',
    iosBundleId: 'com.putonics.prime.petbhore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmXE61oAfj2_yu0TYuh2MmlTicQjxRpM',
    appId: '1:1065959458599:ios:d05ba1a51819356b760b02',
    messagingSenderId: '1065959458599',
    projectId: 'petbhore',
    storageBucket: 'petbhore.appspot.com',
    iosBundleId: 'com.putonics.prime.petbhore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXSdBi_ImQfYl2UbCtU1oYQTwg0Fj8iG0',
    appId: '1:1065959458599:web:c2d2082510893aaa760b02',
    messagingSenderId: '1065959458599',
    projectId: 'petbhore',
    authDomain: 'petbhore.firebaseapp.com',
    storageBucket: 'petbhore.appspot.com',
    measurementId: 'G-Z46K2WVT0B',
  );
}
